# Generated by Django 5.1.4 on 2025-01-24 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('+ Cell', '+ Cell'), ('+ Portfolio', '+ Portfolio'), ('+ Linkedin', '+ Linkedin'), ('+ Location', '+ Location'), ('+ Github', '+ Github'), ('+ Other', '+ Other')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='social',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_social_name'),
        ),
    ]
